sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.stats:
            contexts:   [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts:   [admin]
            
        sonata.block.service.custom: ~

sonata_admin:
    security:
        admin_permissions:

            # Defaults:
            - CREATE
            - LIST
            - DELETE
            - UNDELETE
            - OPERATOR
            - MASTER
    
    
    
    title: Easylink
    title_logo: img/logo1.svg
    templates: 
        layout: NanotechEasylinkAdminBundle::standard_layout.html.twig
        dashboard: NanotechEasylinkAdminBundle:Core:dashboard.html.twig
    dashboard:
        groups:
            
            app.admin.group.admin:
                label: "Configuration"
                label_catalogue: EasylinkBundle
                icon: '<i class="fa fa-home"></i>'
                items:
                    - nanotech_easylink_admin.admin.utilisateur

            app.admin.group.employer:
                label: "Administration"
                label_catalogue: EasylinkBundle
                icon: '<i class="fa fa-home"></i>'
                items:
                - nanotech_easylink_admin.admin.abonnement
                - nanotech_easylink_admin.admin.affectation
                - nanotech_easylink_admin.admin.newletter
                - nanotech_easylink_admin.admin.offre
                - nanotech_easylink_admin.admin.image_offre

            app.admin.group.redacteur:
                label: "Redacteur"
                label_catalogue: EasylinkBundle
                icon: '<i class="fa fa-home"></i>'
                items:
                - nanotech_easylink_admin.admin.avis
                - nanotech_easylink_admin.admin.message
                - nanotech_easylink_admin.admin.specialite
                - nanotech_easylink_admin.admin.sous_specialite

        
