<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * AffectationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectationRepository extends \Doctrine\ORM\EntityRepository
{
}
