<?php

namespace Nanotech\EasylinkBundle\Repository;

use Nanotech\EasylinkBundle\Entity\Offre;
use Nanotech\EasylinkBundle\Entity\Utilisateur;

/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends \Doctrine\ORM\EntityRepository
{


}
