<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * EstimationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimationRepository extends \Doctrine\ORM\EntityRepository
{
}
