<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * ImageOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
