<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * NewletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewletterRepository extends \Doctrine\ORM\EntityRepository
{
}
