<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * Sous_specialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Sous_specialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
