<?php

namespace Nanotech\EasylinkBundle\Repository;

/**
 * sousSpecialiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sousSpecialiteRepository extends \Doctrine\ORM\EntityRepository
{
}
