nanotech_easylink_homepage:
    path:     /
    defaults: { _controller: NanotechEasylinkBundle:Default:index }

nanotech_easylink_annonce:
    path:     /annonce
    defaults: { _controller: NanotechEasylinkBundle:Annonce:annonce }

nanotech_easylink_annonce_sousspecialite:
    path:     /sousspecialite/{id}
    defaults: { _controller: NanotechEasylinkBundle:Annonce:sousspecialite }

nanotech_easylink_contact:
    path:   /contact
    defaults: { _controller: NanotechEasylinkBundle:Default:contact}

nanotech_easylink_about:
    path:   /about
    defaults: { _controller: NanotechEasylinkBundle:Default:about}

nanotech_easylink_anoncepost:
    path:   /anoncepost
    defaults: { _controller: NanotechEasylinkBundle:Annonce:postformannonce}
    methods: POST

nanotech_easylink_blog:
    path:   /blog
    defaults: { _controller: NanotechEasylinkBundle:Blog:index}
